# -*- coding: utf-8 -*-
"""Exp3_FNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mq2moAso0GzFmFIuq92p94C45ws041kG

<a href="https://colab.research.google.com/github/Purushotham011/Neural-Networks-and-DL/blob/main/FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

#Load and Prepare the Data
iris = load_iris()
x = iris.data
y = iris.target.reshape(-1,1)

encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

scaler = StandardScaler()
x = scaler.fit_transform(x)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#Fit data into the model
model =Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

#Train the Model
model.fit(x_train,y_train,epochs=100,batch_size=5)

#Evaluate the model
loss,accuracy = model.evaluate(x_test,y_test)
print(f'Loss:{loss},Accuracy:{accuracy}')

#Make Predictions
predictions = model.predict(x_test)
print('Predictions : ')
print(predictions)

